/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-10-17 06:48:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class editProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/admin/../include/admin/adminHeader.jsp", Long.valueOf(1484104008000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1447727010000L));
    _jspx_dependants.put("/admin/../include/admin/adminNavigator.jsp", Long.valueOf(1484104008000L));
    _jspx_dependants.put("jar:file:/Users/zhaoluyang/JavaProject/Tmall/web/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("jar:file:/Users/zhaoluyang/JavaProject/Tmall/web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 模仿天猫整站j2ee 教程 为how2j.cn 版权所有-->\r\n");
      out.write("<!-- 本教程仅用于学习使用，切勿用于非法用途，由此引起一切后果与本站无关-->\r\n");
      out.write("<!-- 供购买者学习，请勿私自传播，否则自行承担相关法律责任-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 模仿天猫整站j2ee 教程 为how2j.cn 版权所有-->\r\n");
      out.write("<!-- 本教程仅用于学习使用，切勿用于非法用途，由此引起一切后果与本站无关-->\r\n");
      out.write("<!-- 供购买者学习，请勿私自传播，否则自行承担相关法律责任-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"js/jquery/2.0.0/jquery.min.js\"></script>\r\n");
      out.write("\t<link href=\"css/bootstrap/3.3.6/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"js/bootstrap/3.3.6/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link href=\"css/back/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("function checkEmpty(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkNumber(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(isNaN(value)){\r\n");
      out.write("\t\talert(name+ \"必须是数字\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkInt(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(parseInt(value)!=value){\r\n");
      out.write("\t\talert(name+ \"必须是整数\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"a\").click(function(){\r\n");
      out.write("\t\tvar deleteLink = $(this).attr(\"deleteLink\");\r\n");
      out.write("\t\tconsole.log(deleteLink);\r\n");
      out.write("\t\tif(\"true\"==deleteLink){\r\n");
      out.write("\t\t\tvar confirmDelete = confirm(\"确认要删除\");\r\n");
      out.write("\t\t\tif(confirmDelete)\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<!-- 模仿天猫整站j2ee 教程 为how2j.cn 版权所有-->\r\n");
      out.write("<!-- 本教程仅用于学习使用，切勿用于非法用途，由此引起一切后果与本站无关-->\r\n");
      out.write("<!-- 供购买者学习，请勿私自传播，否则自行承担相关法律责任-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"navitagorDiv\">\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top navbar-inverse\">\r\n");
      out.write("\t\t<img style=\"margin-left:10px;margin-right:0px\" class=\"pull-left\" src=\"img/site/tmallbuy.png\" height=\"45px\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"#nowhere\">天猫后台</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_category_list\">分类管理</a>\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_user_list\">用户管理</a>\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_order_list\">订单管理</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>编辑产品</title>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$(\"#editForm\").submit(function() {\r\n");
      out.write("\t\tif (!checkEmpty(\"name\", \"产品名称\"))\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("//\t\t\tif (!checkEmpty(\"subTitle\", \"小标题\"))\r\n");
      out.write("//\t\t\t\treturn false;\r\n");
      out.write("\t\tif (!checkNumber(\"orignalPrice\", \"原价格\"))\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\tif (!checkNumber(\"promotePrice\", \"优惠价格\"))\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\tif (!checkInt(\"stock\", \"库存\"))\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"workingArea\">\r\n");
      out.write("\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t  <li><a href=\"admin_category_list\">所有分类</a></li>\r\n");
      out.write("\t  <li><a href=\"admin_product_list?cid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.category.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("\t  <li class=\"active\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("\t  <li class=\"active\">编辑产品</li>\r\n");
      out.write("\t</ol>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"panel panel-warning editDiv\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">编辑产品</div>\r\n");
      out.write("\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t<form method=\"post\" id=\"editForm\" action=\"admin_product_update\">\r\n");
      out.write("\t\t\t\t<table class=\"editTable\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>产品名称</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>产品小标题</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"subTitle\" name=\"subTitle\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.subTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>原价格</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"orignalPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.orignalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"orignalPrice\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>优惠价格</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"promotePrice\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.promotePrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"promotePrice\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>库存</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"stock\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"stock\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr class=\"submitTR\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"cid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.category.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">提 交</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
