/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-10-15 05:34:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 注册登录_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- Head -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<!-- Meta-Tags -->\r\n");
      out.write("\t<title>æ³¨åç»å½ </title>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <meta name=\"HandheldFriendly\" content=\"True\"/ >\r\n");
      out.write("    <meta name=\"MobileOptimized\" content=\"320\" />\r\n");
      out.write("    <!-- ä¸è¿°metaæ ç­¾*å¿é¡»*æ¾å¨æåé¢ï¼ä»»ä½å¶ä»åå®¹é½*å¿é¡»*è·éå¶åï¼ --><!-- Meta-Tags -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"css/æ³¨åç»å½.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("     <link rel=\"stylesheet\" type=\"text/css\" href=\"css/starbuzz.css\">\r\n");
      out.write("\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/æ³¨åç»å½2.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- //Head -->\r\n");
      out.write("\r\n");
      out.write("<!-- Body -->\r\n");
      out.write("\r\n");
      out.write("<body class=\"home-template\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-static-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("       <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.html\" style=\"color:#00FFFF;font-size: large\">é³åæµæ·çä¸ªäººä¸»é¡µ</a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li id=\"1\"><a href=\"htmls/Webåç«¯.html\" target=\"_blank\">Webåç«¯</a></li>\r\n");
      out.write("            <li><a href=\"htmls/Python.html\" target=\"_blank\">Python</a></li>\r\n");
      out.write("            <li><a href=\"htmls/æ°æ®åº&æå¡å¨.html\"target=\"_blank\">æ°æ®åº&æå¡å¨</a></li>\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">çæ´»æè° <span class=\"caret\"></span></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"çæ´»æè°ä¹æè¶£çå¾ç.html\" target=\"_blank\">æè¶£çå¾ç</a></li>\r\n");
      out.write("                <li><a href=\"#\">æè¶£çäºº&æäº</a></li>\r\n");
      out.write("                <li class=\"dropdown-header\">ä¸ªäººä¸åº</li>\r\n");
      out.write("                <!--æ­¤å¤å¯ä»¥ç¨æ­¤æ ·å¼ï¼æ·»å ä¸æ¡åéæ¨ªçº¿<li role=\"separator\" class=\"divider\"></li>-->\r\n");
      out.write("                <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"#\">ææ&åæ§½</a></li>\r\n");
      out.write("                <li><a href=\"#\">è®¡å&ç®æ </a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a title=\"åäº«è³æ°æµªå¾®å\" charset=\"400-03-10\" id=\"s_sina\"\r\n");
      out.write("href=\"http://v.t.sina.com.cn/share/share.php?appkey=2684493555&url=http://www.flowingsun.com&title=é³åæµæ·çä¸ªäººç½ç«\" target=\"_blank\">\r\n");
      out.write("              åäº«ç½ç«<img src=\"images/ico_sina.gif\" /></a></li>\r\n");
      out.write("            <li><a href=\"æ³¨åç»å½.html\" target=\"_blank\" >æ³¨åç»å½</a></li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\r\n");
      out.write("\t<h1 style=\"color:#00FFFF;font-size:30px\" >æ³¨åç»å½</h1>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container1 w3layouts agileits\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"login w3layouts agileits\">\r\n");
      out.write("\t\t\t<h2 style=\"color:#FFF;font-size:25px\">ç» å½</h2>\r\n");
      out.write("\t\t\t<form action=\"login.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"userid\" placeholder=\"ç¨æ·å\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"userpass\" placeholder=\"å¯ç \" required=\"\">\r\n");
      out.write("\t\t\t<ul class=\"tick w3layouts agileits\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"brand1\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color:#FFF\">è®°ä½æ</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"send-button w3layouts agileits\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ç» å½\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a href=\"#\">è®°ä½å¯ç ?</a>\r\n");
      out.write("\t\t\t<div class=\"social-icons w3layouts agileits\">\r\n");
      out.write("\t\t\t\t<p>- å¶ä»æ¹å¼ç»å½ -</p>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"qq\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icons w3layouts agileits\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"text w3layouts agileits\">QQ</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"weixin w3ls\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icons w3layouts\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"text w3layouts agileits\">å¾®ä¿¡</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"weibo aits\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icons agileits\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"text w3layouts agileits\">å¾®å</span></a></li>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"register w3layouts agileits\">\r\n");
      out.write("\t\t\t<h2 style=\"color:#FFF;font-size:25px\">æ³¨ å</h2>\r\n");
      out.write("\t\t\t<form action=\"register_check.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"username\" placeholder=\"ç¨æ·å\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"email\" placeholder=\"é®ç®±\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"å¯ç \" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"telephone\" placeholder=\"ææºå·ç \" required=\"\">\r\n");
      out.write("\t\t\t<div class=\"send-button w3layouts agileits\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"åè´¹æ³¨å\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer w3layouts agileits\">\r\n");
      out.write("\t\t<p>Copyright &copy; More Templates</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script>window.jQuery || document.write('script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- //Body -->\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
